In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier , AdaBoostClassifier
from sklearn.metrics import accuracy_score , classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
def ans (tp,tn,fp,fn,ac):
    d = pd.Series(index =['tp','tn','fp','fn','spec','sens','ac'])
    
    spec =tn/(tn+fp)
    sens = tp/(tp+fn)
    d = pd.Series(index =['tp','tn','fp','fn','spec','sens','ac'] , data =[tp,tn,fp,fn,spec,sens,ac])
    return d

In [20]:
data = pd.read_csv('C:/Users/Administrator/Desktop/dataset/train (1).csv')

In [4]:
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
dig = data.drop('label' , axis =1)
dig = pd.get_dummies(dig)
dig['label'] = data['label']

In [6]:
dig.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
train, test = train_test_split(dig,
                               test_size=0.3,
                               random_state=100)
train_x = train.drop('label', axis=1)
train_y = train['label']

test_x = test.drop('label', axis=1)
test_y = test['label']

## Decision tree

In [14]:
model = DecisionTreeClassifier(random_state=100, max_depth=13)
model.fit(train_x, train_y)
pred_test = model.predict(test_x)
from sklearn.metrics import accuracy_score
pred_test = model.predict(test_x)
pred_results = pd.DataFrame({
    'actual': test_y,
    'predicted': pred_test
})

print(classification_report(pred_results['actual'],pred_results['predicted']))

             precision    recall  f1-score   support

          0       0.92      0.91      0.91      1242
          1       0.92      0.96      0.94      1424
          2       0.82      0.84      0.83      1199
          3       0.83      0.80      0.82      1296
          4       0.86      0.85      0.85      1204
          5       0.80      0.79      0.80      1178
          6       0.88      0.88      0.88      1250
          7       0.89      0.89      0.89      1284
          8       0.83      0.76      0.79      1236
          9       0.80      0.86      0.83      1287

avg / total       0.86      0.86      0.86     12600

In [15]:
print(classification_report(pred_results['actual'],pred_results['predicted']))

             precision    recall  f1-score   support

          0       0.92      0.91      0.91      1242
          1       0.92      0.96      0.94      1424
          2       0.82      0.84      0.83      1199
          3       0.83      0.80      0.82      1296
          4       0.86      0.85      0.85      1204
          5       0.80      0.79      0.80      1178
          6       0.88      0.88      0.88      1250
          7       0.89      0.89      0.89      1284
          8       0.83      0.76      0.79      1236
          9       0.80      0.86      0.83      1287

avg / total       0.86      0.86      0.86     12600

In [16]:
confusion_matrix(pred_results['actual'],pred_results['predicted']).ravel()

array([1129,    0,   16,   12,    4,   27,   20,    6,   16,   12,    1,
       1370,   11,   14,    4,    6,    5,    5,    4,    4,   21,   11,
       1004,   32,   17,   12,   24,   36,   36,    6,   13,   12,   39,
       1043,   11,   73,   13,   26,   32,   34,    3,   12,   18,   12,
       1024,    7,   15,   15,   19,   79,   23,   14,   13,   59,   17,
        934,   40,    8,   32,   38,   24,   11,   24,    6,   14,   35,
       1096,    6,   22,   12,    3,   19,   30,   15,   10,    9,    0,
       1143,    4,   51,   10,   29,   54,   40,   37,   46,   25,   15,
        934,   46,    2,    7,   15,   22,   56,   20,    3,   28,   24,
       1110], dtype=int64)

In [17]:

accuracy_score(test_y, pred_test)

0.8561111111111112

In [18]:
for m in range(1,15):
    model = DecisionTreeClassifier(random_state=100, max_depth=m)
    model.fit(train_x, train_y)
    pred_test = model.predict(test_x)
    print(m,accuracy_score(test_y, pred_test))

1 0.18896825396825398
2 0.33380952380952383
3 0.4561904761904762
4 0.6316666666666667
5 0.6832539682539682
6 0.7281746031746031
7 0.7745238095238095
8 0.8107936507936508
9 0.8331746031746031
10 0.8444444444444444
11 0.8534126984126984
12 0.8512698412698413
13 0.8561111111111112
14 0.8527777777777777

In [20]:
from sklearn.model_selection import GridSearchCV

In [25]:
cv_model.best_params_

{'max_depth': 15}

In [21]:
params = {'max_depth': list(range(1,30)) , 'criterion': ['gini','entropy']}
base_estimator = DecisionTreeClassifier(random_state=100)
cv_model = GridSearchCV(base_estimator , param_grid = params ,cv =10 ,scoring= 'accuracy')
cv_model.fit(train_x , train_y)

GridSearchCV(cv=10, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 'criterion': ['gini', 'entropy']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

# Random Forest

In [23]:
test = pd.read_csv('test.csv')

In [24]:
test.columns

Index(['pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=784)

In [25]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(random_state=100, n_estimators=800)

model_rf.fit(train_x, train_y)
pred = model_rf.predict(test)
pred1 = model_rf.predict(test_x)
print(accuracy_score(test_y, pred1))
print(classification_report(test_y, pred1))

0.9647619047619047
             precision    recall  f1-score   support

          0       0.98      0.99      0.98      1242
          1       0.98      0.98      0.98      1424
          2       0.95      0.96      0.96      1199
          3       0.96      0.95      0.96      1296
          4       0.96      0.96      0.96      1204
          5       0.97      0.96      0.97      1178
          6       0.97      0.99      0.98      1250
          7       0.97      0.96      0.96      1284
          8       0.96      0.95      0.95      1236
          9       0.94      0.94      0.94      1287

avg / total       0.96      0.96      0.96     12600

In [16]:
df_pred_rf = pd.DataFrame({'ImageId': list(range(1, len(pred)+1)), 'Label': pred})

In [17]:
df_pred_rf

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
5            6      7
6            7      0
7            8      3
8            9      0
9           10      3
10          11      5
11          12      7
12          13      4
13          14      0
14          15      4
15          16      3
16          17      3
17          18      1
18          19      9
19          20      0
20          21      9
21          22      1
22          23      1
23          24      5
24          25      7
25          26      4
26          27      2
27          28      7
28          29      4
29          30      7
...        ...    ...
27970    27971      5
27971    27972      0
27972    27973      4
27973    27974      8
27974    27975      0
27975    27976      3
27976    27977      6
27977    27978      0
27978    27979      1
27979    27980      9
27980    27981      3
27981    27982      1
27982    27983      1
27983    27984      0
27984    27985      4
27985    27986      5
27986    27987      2
27987    27988      2
27988    27989      8
27989    27990      6
27990    27991      7
27991    27992      6
27992    27993      1
27993    27994      9
27994    27995      7
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [ ]:
df_pred_rf.to_csv('submission.csv', index = False)

In [18]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
train = pd.read_csv('C:/Users/Administrator/Desktop/dataset/train (1).csv')
test = pd.read_csv('test.csv')
#sample_submission = pd.read_csv('sample_submission.csv')
train_x = train.drop('label', axis=1)
train_y = train['label']
model_rf = RandomForestClassifier(random_state=100, n_estimators=800)

model_rf.fit(train_x, train_y)
pred = model_rf.predict(test)
df_pred_rf = pd.DataFrame({'ImageId': list(range(1, len(pred)+1)), 'Label': pred})
df_pred_rf.to_csv('submission.csv', index = False)